# Tiltfile for agent-farmer development environment
# This file was auto-generated by agent-farmer

# Load the docker-compose file
docker_compose('docker-compose.yml')

# Set up port forwarding
# You can customize this based on your services
# Example:
# k8s_resource('your-service', port_forwards='3000:3000')

# Environment variables are available:
# TASK_NAME - the name of the current agent task
# TASK_HOSTNAME - the generated hostname for this task
# TASK_PORT - the base port for this task

print("Starting development environment for task: " + os.getenv('TASK_NAME', 'unknown'))
print("Hostname: " + os.getenv('TASK_HOSTNAME', 'unknown'))
print("Port: " + os.getenv('TASK_PORT', '3000'))
